---
title: "Voter Guides"
author: "Maddy Pfaff and Lucia Vaccaro"
date: "Last updated on `r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: kable
---

<!--
Comments in HTML are like this! 
-->



## States with or without Voter Guides

45 out of 50 states produce voter ballot guides and are published by the state’s Secretary of State (New Jersey and North Dakota do not have guides, but New Jersey does send out a sample ballot to voters). For the focus of this investigation, we will be focusing on voter guides that provide information on ballot initiatives (the opportunity for citizens to participate in direct democracy and vote for/against a legislative proposal), which can be referred to as ballot measure voter guides. As explained by Ballotpedia, the ballot measure voter guides “are specific booklets or pamphlets published by state governments to educate voters on the initiatives, referendums, and referrals they will be voting on in upcoming elections”.^[“Features of Official Voter Guides, Compared by State.”, Ballotpedia.org] 


```{r, echo = FALSE, message= FALSE, warning =FALSE}

#loading necessary packages
library(tidyverse)
library(sf)
library(maps)
library(USAboundaries)
library(tmaptools)
library(patchwork)
library(ggpubr)
#creating US map from USABoundries
USA_map <-  maps::map("state", plot = FALSE, fill = TRUE)

USA_sf <- USA_map %>% 
  st_as_sf(crs = 4326)
#reading csv to load information on voter guides
voter_guide <- read.csv("data/vg_boole.csv") %>% 
  rename("vg_bool" = "VG_Y.N")

#using USABoundries to make a map of continental US
USA_map <-  maps::map("state", plot = FALSE, fill = TRUE)

#making sf and changing name to join with other datasets
USA_sf <- USA_map %>% 
  st_as_sf(crs = 4326) %>% 
  rename("state" = "ID")


#joining to give geometry to voter guide information
voter_guide_geom <-USA_sf %>% 
  right_join(voter_guide, by= "state")

#plotting map showing which states create voter guides
ggplot()+
  geom_sf(data = USA_sf)+
  geom_sf(data  = voter_guide_geom, aes(fill = vg_bool)) +
  theme(rect = element_blank(), axis.text.x = element_blank(), 
        axis.text.y = element_blank(), axis.ticks = element_blank())+
  labs(title = "States That Publish Voter Guides", fill = "Does this state publish\na voter guide?")+
  scale_fill_grey()


```


